var searchData=
[
  ['matrixfreegmres_0',['MatrixFreeGMRES',['../classcgmres_1_1detail_1_1_matrix_free_g_m_r_e_s.html#a5bd6186e6c818014bfd52049dbec6c5c',1,'cgmres::detail::MatrixFreeGMRES']]],
  ['multipleshootingcgmressolver_1',['MultipleShootingCGMRESSolver',['../classcgmres_1_1_multiple_shooting_c_g_m_r_e_s_solver.html#ab4d7d8529ba7c1237a46a5c79eb4cc44',1,'cgmres::MultipleShootingCGMRESSolver::MultipleShootingCGMRESSolver(const OCP &amp;ocp, const Horizon &amp;horizon, const SolverSettings &amp;settings)'],['../classcgmres_1_1_multiple_shooting_c_g_m_r_e_s_solver.html#a7c7f7be93bce7546a80c0c92981966f0',1,'cgmres::MultipleShootingCGMRESSolver::MultipleShootingCGMRESSolver()=default']]],
  ['multipleshootingnlp_2',['MultipleShootingNLP',['../classcgmres_1_1detail_1_1_multiple_shooting_n_l_p.html#a01af346750f29ff83c7749befba32e2c',1,'cgmres::detail::MultipleShootingNLP::MultipleShootingNLP(const OCP &amp;ocp, const Horizon &amp;horizon)'],['../classcgmres_1_1detail_1_1_multiple_shooting_n_l_p.html#a5838cf1e52291a7d8433ec7227c000af',1,'cgmres::detail::MultipleShootingNLP::MultipleShootingNLP()=default']]],
  ['multiply_5fhdummy_5finv_3',['multiply_hdummy_inv',['../classcgmres_1_1detail_1_1_multiple_shooting_n_l_p.html#a5adf5b86025dff959c11839aa901f441',1,'cgmres::detail::MultipleShootingNLP::multiply_hdummy_inv()'],['../namespacecgmres_1_1detail_1_1ubounds.html#a85eb8046d0143fdaabe0a7ce83f34f0a',1,'cgmres::detail::ubounds::multiply_hdummy_inv(const MatrixBase&lt; VectorType1 &gt; &amp;dummy, const MatrixBase&lt; VectorType2 &gt; &amp;mu, const MatrixBase&lt; VectorType3 &gt; &amp;hdummy, const MatrixBase&lt; VectorType4 &gt; &amp;hmu, const MatrixBase&lt; VectorType5 &gt; &amp;hdummy_multiplied)'],['../namespacecgmres_1_1detail_1_1ubounds.html#abc8546f327a2213163f37a02cd03a0e2',1,'cgmres::detail::ubounds::multiply_hdummy_inv(const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;dummy, const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;mu, const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;fonc_hdummy, const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;fonc_hmu, std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;fonc_hdummy_inv)']]],
  ['multiply_5fhmu_5finv_4',['multiply_hmu_inv',['../classcgmres_1_1detail_1_1_multiple_shooting_n_l_p.html#ae4231f9237f71d86acb922f6458140d5',1,'cgmres::detail::MultipleShootingNLP::multiply_hmu_inv()'],['../namespacecgmres_1_1detail_1_1ubounds.html#a63cd145aca2a19fe27c1c62fc4cbda62',1,'cgmres::detail::ubounds::multiply_hmu_inv(const MatrixBase&lt; VectorType1 &gt; &amp;dummy, const MatrixBase&lt; VectorType2 &gt; &amp;mu, const MatrixBase&lt; VectorType3 &gt; &amp;hdummy, const MatrixBase&lt; VectorType4 &gt; &amp;hmu, const MatrixBase&lt; VectorType5 &gt; &amp;hdummy_multiplied, const MatrixBase&lt; VectorType6 &gt; &amp;hmu_multiplied)'],['../namespacecgmres_1_1detail_1_1ubounds.html#aabf700db2bc45b5329bb06826fc7dfec',1,'cgmres::detail::ubounds::multiply_hmu_inv(const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;dummy, const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;mu, const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;fonc_hdummy, const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;fonc_hmu, const std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;fonc_hdummy_inv, std::array&lt; Vector&lt; OCP::nub &gt;, N &gt; &amp;fonc_hmu_inv)']]],
  ['muopt_5',['muopt',['../classcgmres_1_1_multiple_shooting_c_g_m_r_e_s_solver.html#a969bf8355fab25585659063a0fa3a321',1,'cgmres::MultipleShootingCGMRESSolver::muopt()'],['../classcgmres_1_1_single_shooting_c_g_m_r_e_s_solver.html#a884060621482f374f6055ccb39baf9fc',1,'cgmres::SingleShootingCGMRESSolver::muopt()'],['../classcgmres_1_1_zero_horizon_o_c_p_solver.html#a63e5318c77c73f1bf600bc97ae673bdd',1,'cgmres::ZeroHorizonOCPSolver::muopt()']]]
];
